CONFIG_MAIN_STACK_SIZE=2048

CONFIG_I2C=y
CONFIG_I2C_TARGET=y


CONFIG_PM_DEVICE=y

CONFIG_BOOT_BANNER=n
CONFIG_PRINTK=n
CONFIG_UART_CONSOLE=n
CONFIG_CONSOLE=n

CONFIG_LOG=n
# CONFIG_LOG_DEFAULT_LEVEL=3
# CONFIG_LOG_BACKEND_RTT=y
# CONFIG_LOG_MODE_IMMEDIATE=y
# CONFIG_USE_SEGGER_RTT=y
# CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=4096
# CONFIG_SEGGER_RTT_BUFFER_SIZE_DOWN=16